'use client'

import { useMemo, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Bell, BriefcaseBusiness, Check, ChevronRight, CircleHelp, Home, LineChart, Menu, Plus, Search, Settings2, Star, UserRound, WalletCards, X } from 'lucide-react'

type Tab = 'Home' | 'Markets' | 'Portfolio' | 'Orders' | 'Profile'
type Side = 'Buy' | 'Sell'
type Asset = { name: string; ticker: string; price: number; change: number; up: boolean }

const assets: Asset[] = [
  { name: 'Reliance Industries', ticker: 'RELIANCE', price: 1482.5, change: 1.26, up: true },
  { name: 'HDFC Bank', ticker: 'HDFCBANK', price: 1756.8, change: 0.84, up: true },
  { name: 'Tata Motors', ticker: 'TATAMOTORS', price: 982.15, change: -0.42, up: false },
  { name: 'Infosys', ticker: 'INFY', price: 1464.2, change: 1.04, up: true },
]
const money = (value: number) => `₹${value.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

function Brand() { return <div className="brand"><span className="brand-mark">c</span><strong>citron</strong></div> }
function Delta({ asset }: { asset: Asset }) { return <span className={asset.up ? 'delta positive' : 'delta negative'}>{asset.up ? <ArrowUpRight /> : <ArrowDownRight />}{asset.up ? '+' : ''}{asset.change.toFixed(2)}%</span> }
function Chart() { return <svg className="chart" viewBox="0 0 360 92" preserveAspectRatio="none" role="img" aria-label="Simulated upward portfolio performance"><path d="M0 72 C28 64 34 78 58 55 S88 66 111 43 S139 49 164 37 S188 48 211 25 S246 38 270 19 S303 31 328 10 S349 18 360 4 V92 H0Z" fill="var(--citron-soft)"/><path d="M0 72 C28 64 34 78 58 55 S88 66 111 43 S139 49 164 37 S188 48 211 25 S246 38 270 19 S303 31 328 10 S349 18 360 4" fill="none" stroke="var(--citron)" strokeWidth="3" strokeLinecap="round"/></svg> }
function TopBar({ onMenu, onNotifications }: { onMenu: () => void; onNotifications: () => void }) { return <header className="topbar"><button className="icon-button" aria-label="Open menu" onClick={onMenu}><Menu /></button><Brand/><div className="top-actions"><button className="icon-button notification" aria-label="Notifications" onClick={onNotifications}><Bell/><i/></button><button className="avatar" aria-label="Open profile">AK</button></div></header> }
function BottomNav({ tab, setTab }: { tab: Tab; setTab: (tab: Tab) => void }) { const items: [Tab, typeof Home][] = [['Home', Home], ['Markets', LineChart], ['Portfolio', WalletCards], ['Orders', BriefcaseBusiness], ['Profile', UserRound]]; return <nav className="bottom-nav" aria-label="Primary navigation">{items.map(([name, Icon]) => <button key={name} className={tab === name ? 'nav-item active' : 'nav-item'} onClick={() => setTab(name)}><Icon/><span>{name}</span></button>)}</nav> }
function SectionTitle({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { return <div className="section-title"><h2>{title}</h2>{action && <button className="text-button" onClick={onAction}>{action}<ChevronRight/></button>}</div> }
function AssetRow({ asset, watched, onWatch, onSelect }: { asset: Asset; watched: boolean; onWatch: () => void; onSelect: () => void }) { return <div className="asset-row"><button className="asset-main" onClick={onSelect}><span className="asset-icon">{asset.ticker[0]}</span><span className="asset-name"><b>{asset.name}</b><small>{asset.ticker} · NSE</small></span><span className="asset-price"><b>{money(asset.price)}</b><Delta asset={asset}/></span></button><button className={watched ? 'star watched' : 'star'} aria-label={watched ? `Remove ${asset.ticker} from watchlist` : `Add ${asset.ticker} to watchlist`} onClick={onWatch}><Star/></button></div> }
function HomeView({ openOrder, setTab, watchlist, toggleWatch }: { openOrder: (side: Side, asset?: Asset) => void; setTab: (tab: Tab) => void; watchlist: string[]; toggleWatch: (ticker: string) => void }) { return <><div className="greeting"><div><p className="eyebrow">DEMO ACCOUNT · 02 OCT 2026</p><h1>Good morning, Aanya</h1></div><button className="round-action" onClick={() => openOrder('Buy')} aria-label="Buy an asset"><Plus/></button></div><section className="portfolio-hero"><div className="hero-top"><span>Total portfolio value</span><span className="demo-label">SIMULATED</span></div><strong>₹2,48,650<span>.40</span></strong><div className="hero-meta"><span className="positive">+₹4,820.20 · +1.98%</span><span>Today&apos;s P&amp;L</span></div><Chart/></section><div className="quick-actions"><button onClick={() => openOrder('Buy')}><span className="qa-icon citron"><ArrowUpRight/></span><b>Buy</b></button><button onClick={() => openOrder('Sell')}><span className="qa-icon ink"><ArrowDownRight/></span><b>Sell</b></button><button onClick={() => setTab('Profile')}><span className="qa-icon soft"><Plus/></span><b>Add funds</b></button></div><section><SectionTitle title="Market snapshot" action="View all" onAction={() => setTab('Markets')}/><div className="market-strip"><div><span>NIFTY 50</span><b>23,465.10</b><span className="positive">+0.74%</span></div><div><span>SENSEX</span><b>77,301.14</b><span className="positive">+0.63%</span></div></div></section><section><SectionTitle title="Your watchlist" action="Manage" onAction={() => setTab('Markets')}/><div className="watchlist">{assets.slice(0, 3).map(asset => <AssetRow key={asset.ticker} asset={asset} watched={watchlist.includes(asset.ticker)} onWatch={() => toggleWatch(asset.ticker)} onSelect={() => openOrder('Buy', asset)}/>)}</div></section><section><SectionTitle title="Explore products" action="See marketplace" onAction={() => setTab('Profile')}/><button className="product-card" onClick={() => setTab('Profile')}><span className="product-visual">↗</span><span><small className="tag">FEATURED LISTING</small><b>Solaris Green Energy Fund</b><small>Curated basket · Moderate risk</small></span><ChevronRight/></button></section></> }
function MarketsView({ openOrder, watchlist, toggleWatch }: { openOrder: (side: Side, asset?: Asset) => void; watchlist: string[]; toggleWatch: (ticker: string) => void }) { const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const filtered = useMemo(() => assets.filter(a => `${a.name} ${a.ticker}`.toLowerCase().includes(query.toLowerCase())).filter(a => filter === 'All' || (filter === 'Gainers' ? a.up : !a.up)), [query, filter]); return <><div className="page-heading"><div><p className="eyebrow">MARKETS · DEMO DATA</p><h1>Find your next move</h1></div><button className="icon-button" aria-label="Market settings"><Settings2/></button></div><label className="search-box"><Search/><input aria-label="Search stocks, ETFs and funds" placeholder="Search stocks, ETFs and funds" value={query} onChange={e => setQuery(e.target.value)}/></label><div className="category-row">{['All', 'Gainers', 'Losers'].map(item => <button key={item} className={filter === item ? 'selected' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div><section><SectionTitle title="Instruments" action="Sort"/><div className="watchlist">{filtered.length ? filtered.map(asset => <AssetRow key={asset.ticker} asset={asset} watched={watchlist.includes(asset.ticker)} onWatch={() => toggleWatch(asset.ticker)} onSelect={() => openOrder('Buy', asset)}/>) : <p className="empty">No instruments match your search.</p>}</div></section></> }
function PortfolioView() { return <><div className="page-heading"><div><p className="eyebrow">PORTFOLIO</p><h1>Your investments</h1></div></div><div className="summary-card"><span>Invested amount</span><b>₹2,18,400.00</b><div className="summary-bottom"><span>Overall returns</span><strong className="positive">+₹30,250.40 · +13.85%</strong></div></div><div className="category-row wide"><button className="selected">Holdings <span>6</span></button><button>Positions</button></div><section><SectionTitle title="Holdings" action="Sort"/><div className="holding-list">{assets.slice(0, 3).map((asset, i) => <div className="holding-row" key={asset.ticker}><span className="asset-icon">{asset.ticker[0]}</span><span className="asset-name"><b>{asset.ticker}</b><small>{[12, 8, 15][i]} shares</small></span><span className="asset-price"><b>{money(asset.price * [12, 8, 15][i])}</b><Delta asset={asset}/></span></div>)}</div></section><section><SectionTitle title="Allocation"/><div className="allocation"><div className="donut"><b>₹2.4L</b><small>Total</small></div><div className="legend"><span>Equity <b>68%</b></span><span>ETFs <b>20%</b></span><span>Funds <b>12%</b></span></div></div></section></> }
function OrdersView() { return <><div className="page-heading"><div><p className="eyebrow">ACTIVITY</p><h1>Orders</h1></div></div><div className="category-row wide"><button className="selected">All <span>8</span></button><button>Open <span>2</span></button><button>Completed</button></div><section className="orders-list">{[['Buy','Infosys','INFY','12 shares','Completed'],['Sell','Tata Motors','TATAMOTORS','8 shares','Open'],['Buy','HDFC Bank','HDFCBANK','5 shares','Completed']].map(([side,name,ticker,qty,status]) => <article className="order-card" key={ticker}><div className="order-line"><span className={side === 'Buy' ? 'side buy' : 'side sell'}>{side}</span><span className="order-status">{status}</span></div><div className="order-main"><span className="asset-icon">{ticker[0]}</span><span className="asset-name"><b>{name}</b><small>{ticker} · {qty}</small></span><span className="asset-price"><b>{status === 'Open' ? '₹7,888.00' : '₹17,570.40'}</b><small>Today, 10:42 AM</small></span></div>{status === 'Open' && <button className="cancel-button">Cancel order</button>}</article>)}</section></> }
function ProfileView({ cvd, setCvd }: { cvd: boolean; setCvd: (v: boolean) => void }) { return <><div className="page-heading"><div><p className="eyebrow">ACCOUNT</p><h1>Your profile</h1></div><button className="icon-button"><Settings2/></button></div><div className="profile-card"><div className="profile-avatar">AK</div><div><h3>Aanya Kapoor</h3><p>aanya.kapoor@email.com</p><span className="verified">✓ Verified account</span></div><ChevronRight/></div><section><SectionTitle title="Preferences"/><div className="settings-list"><button className="setting-row"><span className="setting-icon"><Settings2/></span><span><b>Price colors</b><small>{cvd ? 'Color-vision safe' : 'Green up / Red down'}</small></span><span className={cvd ? 'toggle on' : 'toggle'} onClick={e => { e.stopPropagation(); setCvd(!cvd) }}><i/></span></button><button className="setting-row"><span className="setting-icon"><Bell/></span><span><b>Notifications</b><small>Price alerts and order updates</small></span><ChevronRight/></button><button className="setting-row"><span className="setting-icon"><CircleHelp/></span><span><b>Help &amp; support</b><small>We&apos;re here to help</small></span><ChevronRight/></button></div></section><section><SectionTitle title="Marketplace"/><button className="listing-banner"><span><small className="tag">SELL YOUR PRODUCTS</small><b>Turn your ideas into income.</b><small>List a product for the Citron community.</small></span><span className="small-primary"><Plus/> List product</span></button></section><button className="logout">Log out</button></> }
function OrderSheet({ side: initialSide, asset: initialAsset, close }: { side: Side; asset?: Asset; close: () => void }) { const [side, setSide] = useState(initialSide); const [asset] = useState(initialAsset || assets[3]); const [quantity, setQuantity] = useState('10'); const [step, setStep] = useState<'form'|'review'|'success'>('form'); const available = side === 'Sell' ? 42 : 68; const total = Number(quantity || 0) * asset.price; const invalid = !Number.isInteger(Number(quantity)) || Number(quantity) <= 0 || Number(quantity) > available; return <div className="modal-backdrop" onClick={close}><div className="order-sheet" role="dialog" aria-modal="true" aria-labelledby="order-title" onClick={e => e.stopPropagation()}><div className="sheet-handle"/><div className="sheet-head"><div><span className="eyebrow">SIMULATED ORDER · {step === 'review' ? 'REVIEW' : step === 'success' ? 'COMPLETE' : 'FORM'}</span><h2 id="order-title">{step === 'success' ? `${side} order placed` : `${side} ${asset.name}`}</h2><p>{asset.ticker} · {money(asset.price)} <Delta asset={asset}/></p></div><button className="icon-button" onClick={close} aria-label="Close order"><X/></button></div>{step === 'success' ? <div className="success-state"><span className="success-icon"><Check/></span><p>Your simulated order is complete.</p><div className="detail"><span>Order ID</span><b>CTN-021026-1042</b><span>Quantity</span><b>{quantity} shares</b><span>Estimated amount</span><b>{money(total)}</b></div><button className="primary-button" onClick={close}>Done</button></div> : <>{step === 'form' && <><div className="buy-sell"><button className={side === 'Buy' ? 'active' : ''} onClick={() => setSide('Buy')}>Buy</button><button className={side === 'Sell' ? 'active sell-active' : ''} onClick={() => setSide('Sell')}>Sell</button></div><label className="field">Quantity <span>Available: {available}</span><input autoFocus inputMode="numeric" aria-invalid={invalid} value={quantity} onChange={e => setQuantity(e.target.value)}/>{invalid && <small className="error">Enter a whole number between 1 and {available}.</small>}</label></>}{step === 'review' && <div className="review"><div><span>Asset</span><b>{asset.ticker}</b></div><div><span>Order type</span><b>Market</b></div><div><span>Quantity</span><b>{quantity} shares</b></div><div><span>Estimated total</span><b>{money(total)}</b></div><div><span>Available balance</span><b>₹68,420.00</b></div></div>}<button className="primary-button" disabled={invalid} onClick={() => step === 'form' ? setStep('review') : setStep('success')}>{step === 'form' ? 'Review order' : `Confirm ${side.toLowerCase()}`}<ChevronRight/></button><p className="demo-note">Demo market data. No real funds or trades are involved.</p></>}</div></div> }
function MenuSheet({ close, setTab }: { close: () => void; setTab: (tab: Tab) => void }) { return <div className="modal-backdrop" onClick={close}><aside className="menu-sheet" onClick={e => e.stopPropagation()}><div className="sheet-head"><div><span className="eyebrow">ACCOUNT</span><h2>Quick menu</h2></div><button className="icon-button" onClick={close} aria-label="Close menu"><X/></button></div><button onClick={() => { setTab('Profile'); close() }}><UserRound/> Profile<ChevronRight/></button><button onClick={() => { setTab('Orders'); close() }}><Bell/> Notifications<ChevronRight/></button><button onClick={() => { setTab('Profile'); close() }}><Settings2/> Settings<ChevronRight/></button><button><CircleHelp/> Help &amp; support<ChevronRight/></button><button className="logout">Log out</button></aside></div> }
export default function Page() { const [tab, setTab] = useState<Tab>('Home'); const [order, setOrder] = useState<{ side: Side; asset?: Asset } | null>(null); const [menu, setMenu] = useState(false); const [cvd, setCvd] = useState(false); const [watchlist, setWatchlist] = useState(['RELIANCE', 'HDFCBANK']); const toggleWatch = (ticker: string) => setWatchlist(list => list.includes(ticker) ? list.filter(item => item !== ticker) : [...list, ticker]); const content = tab === 'Markets' ? <MarketsView openOrder={(side, asset) => setOrder({ side, asset })} watchlist={watchlist} toggleWatch={toggleWatch}/> : tab === 'Portfolio' ? <PortfolioView/> : tab === 'Orders' ? <OrdersView/> : tab === 'Profile' ? <ProfileView cvd={cvd} setCvd={setCvd}/> : <HomeView openOrder={(side, asset) => setOrder({ side, asset })} setTab={setTab} watchlist={watchlist} toggleWatch={toggleWatch}/>; return <main className="app-shell"><TopBar onMenu={() => setMenu(true)} onNotifications={() => setTab('Orders')}/><div className="screen-content">{content}</div><BottomNav tab={tab} setTab={setTab}/>{order && <OrderSheet {...order} close={() => setOrder(null)}/>} {menu && <MenuSheet close={() => setMenu(false)} setTab={setTab}/>}</main> }
